/* Warning: This file is generated by ./collate-test - do not modify directly! */
extern void test_snippet1();
extern void test_snippetstem1();
extern void test_snippetphrase1();
extern void test_snippetmisc1();
extern void test_snippet_termcover1();
extern void test_snippet_termcover2();
extern void test_snippet_empty();
extern void test_snippet_start_nonspace();
extern void test_snippet_small_zerolength();
extern void test_snippet_ngrams();
extern void test_snippet_empty_mset();
extern void test_snippet_empty_mset2();
