/* Warning: This file is generated by ./collate-test - do not modify directly! */
extern void test_latlongpostingsource1();
extern void test_latlongcoords1();
extern void test_latlongmetric1();
extern void test_latlongmetric2();
extern void test_latlongkeymaker1();
