/* Warning: This file is generated by ./collate-test - do not modify directly! */
extern void test_termgen1();
extern void test_tg_spell1();
extern void test_tg_spell2();
extern void test_tg_max_word_length1();
