/* Warning: This file is generated by ./collate-test - do not modify directly! */
extern void test_serialise_document1();
extern void test_serialise_document2();
extern void test_serialise_query1();
extern void test_serialise_query2();
extern void test_serialise_query3();
extern void test_serialise_query4();
extern void test_double_register_leak();
extern void test_registry1();
extern void test_registry2();
extern void test_registry3();
