/** @file
 *  @brief Include headers for all Snowball stemmers
 */
/* Warning: This file is generated by ./languages/collate-sbl - do not modify directly! */
/* Copyright (C) 2007,2012,2013,2015 Olly Betts
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
 */

#ifndef XAPIAN_INCLUDED_ALLSNOWBALLHEADERS_H
#define XAPIAN_INCLUDED_ALLSNOWBALLHEADERS_H

#include "arabic.h"
#include "armenian.h"
#include "basque.h"
#include "catalan.h"
#include "danish.h"
#include "dutch.h"
#include "earlyenglish.h"
#include "english.h"
#include "finnish.h"
#include "french.h"
#include "german.h"
#include "german2.h"
#include "hungarian.h"
#include "indonesian.h"
#include "irish.h"
#include "italian.h"
#include "kraaij_pohlmann.h"
#include "lithuanian.h"
#include "lovins.h"
#include "nepali.h"
#include "norwegian.h"
#include "porter.h"
#include "portuguese.h"
#include "romanian.h"
#include "russian.h"
#include "spanish.h"
#include "swedish.h"
#include "tamil.h"
#include "turkish.h"

#endif
